### ISSUE TITLE
Robotjs Scroll Mouse not working

### ISSUE THREAD

**Issue by Lvschaitanya** [akanshSirohi/akanshSirohi#1]
I am using robotjs for my project and the changes u have mentioned in the [issue](https://github.com/octalmage/robotjs/issues/663) have already present in the mouse.c file and the scrolling is not working. Can you please suggest me the way to solve this.

**Comment by akanshSirohi** [comment]
Hey @Lvschaitanya , actually I already made pull request about this issue but it isn't merged yet, and the changes I have mentioned aren't implemented in the official RobotJS repository. I am attaching screenshots below so you can see and do the changes by yourself.

![1](https://user-images.githubusercontent.com/34837239/122713513-6d3a0600-d283-11eb-92b5-2653f6c285f6.jpg)
These are the required changes you have to make in mouse.c

![2](https://user-images.githubusercontent.com/34837239/122713570-8478f380-d283-11eb-9d16-9694cb7f2055.jpg)
This is original file mouse.c I have just captured this from their repo
